# Generated by Django 5.2.6 on 2025-09-12 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sip_status', models.BooleanField(default=False)),
                ('sip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sip_topup', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('health_status', models.BooleanField(default=False)),
                ('health_cover', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('health_topup', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('health_product', models.CharField(blank=True, max_length=200, null=True)),
                ('life_status', models.BooleanField(default=False)),
                ('life_cover', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('life_product', models.CharField(blank=True, max_length=200, null=True)),
                ('motor_status', models.BooleanField(default=False)),
                ('motor_insured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('motor_product', models.CharField(blank=True, max_length=200, null=True)),
                ('pms_status', models.BooleanField(default=False)),
                ('pms_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pms_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Unmapped', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.employee')),
            ],
        ),
    ]
