# Generated by Django 5.2.6 on 2025-09-12 18:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('SIP', 'SIP'), ('Lumpsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS')], max_length=50, unique=True)),
                ('unit_amount', models.DecimalField(decimal_places=2, help_text='Base unit (e.g., 1000 or 100000)', max_digits=14)),
                ('points_per_unit', models.DecimalField(decimal_places=3, help_text='Points awarded per unit_amount', max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Incentive Rule',
                'verbose_name_plural': 'Incentive Rules',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-13 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='incentive_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='points',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Lumsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS')], max_length=50),
        ),
        migrations.CreateModel(
            name='MonthlyIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_points', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_incentives', to='clients.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
