# Generated by Django 5.2.6 on 2025-09-13 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_incentiverule_sale_created_at_sale_incentive_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
