# Generated by Django 5.2.6 on 2025-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cover_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
