# Generated by Django 5.2.6 on 2025-09-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_sale_cover_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('SIP', 'SIP'), ('Lumsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS')], max_length=50)),
                ('target_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='clients.employee')),
            ],
            options={
                'unique_together': {('employee', 'product', 'target_type')},
            },
        ),
    ]
