# Generated by Django 5.2.6 on 2025-09-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_target'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('product', 'target_type')},
        ),
        migrations.RemoveField(
            model_name='target',
            name='employee',
        ),
    ]
