# Generated by Django 5.2.6 on 2025-09-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_target_unique_together_remove_target_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTargetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('SIP', 'SIP'), ('Lumsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS')], max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.employee')),
            ],
            options={
                'unique_together': {('employee', 'product', 'year', 'month')},
            },
        ),
    ]
