# Generated by Django 5.2.6 on 2025-09-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_monthlytargethistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytargethistory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='monthlytargethistory',
            name='points_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytargethistory',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
