# Generated by Django 5.2.6 on 2025-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_monthlytargethistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiverule',
            name='product',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Lumsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS')], max_length=50, unique=True),
        ),
    ]
