# Generated by Django 5.2.6 on 2025-09-19 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_incentiverule_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'Not Called'), ('called', 'Called'), ('no_answer', 'No Answer'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('busy', 'Busy'), ('wrong_number', 'Wrong Number')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.employee')),
                ('calling_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='clients.callinglist')),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.employee')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='clients.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('call_followup', 'Call Follow-up'), ('meeting', 'Meeting'), ('task', 'Task'), ('reminder', 'Reminder')], default='task', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='clients.employee')),
                ('related_prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.prospect')),
            ],
        ),
    ]
