# Generated by Django 5.2.6 on 2025-10-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_prospect_email_prospect_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='clients.client'),
        ),
    ]
