# Generated by Django 5.2.7 on 2025-10-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_messagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(help_text='Use any placeholders from the Client model like {{ name }}, {{ phone }}, {{ sip_amount }} etc.'),
        ),
    ]
