# Generated by Django 5.2.7 on 2025-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_redemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
