# Generated by Django 4.2.25 on 2026-01-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0030_employee_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetSipEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_type", models.CharField(choices=[("fresh", "SIP Fresh"), ("stopped", "SIP Stopped")], max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-date", "-created_at"]},
        ),
    ]
