# Generated by Django 4.2.25 on 2026-02-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_lead_followup_and_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiverule',
            name='product',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Lumsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS'), ('COB', 'COB')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='product',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Lumsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS'), ('COB', 'COB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Lumsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS'), ('COB', 'COB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='product',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Lumsum', 'Lumsum'), ('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('Motor Insurance', 'Motor Insurance'), ('PMS', 'PMS'), ('COB', 'COB')], max_length=50),
        ),
    ]
