# Generated by Django 4.2.25 on 2026-02-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_client',
            field=models.ForeignKey(blank=True, help_text='Client created from this lead via conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='clients.client'),
        ),
    ]
