# Generated by Django 4.2.25 on 2026-02-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_alter_calendarevent_scheduled_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Cumulative monthly amount threshold', max_digits=14)),
                ('payout', models.DecimalField(decimal_places=2, help_text='Points/payout awarded when threshold is reached', max_digits=14)),
                ('label', models.CharField(blank=True, help_text="Optional label, e.g. 'Gold Slab'", max_length=100)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='clients.incentiverule')),
            ],
            options={
                'verbose_name': 'Incentive Slab',
                'verbose_name_plural': 'Incentive Slabs',
                'ordering': ['-threshold'],
                'unique_together': {('rule', 'threshold')},
            },
        ),
    ]
