# Generated by Django 4.2.25 on 2026-03-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_incentive_slabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(default='Kadlag Investment', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Firm address')),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('website', models.URLField(blank=True, help_text='Company website')),
                ('logo', models.ImageField(blank=True, help_text='Firm logo (recommended: 200x60px PNG with transparent background)', null=True, upload_to='firm_logo/')),
                ('primary_color', models.CharField(default='#E5B740', help_text='Primary brand color (hex format, e.g., #E5B740)', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firm Settings',
                'verbose_name_plural': 'Firm Settings',
            },
        ),
    ]
