# Generated by Django 5.2.9 on 2026-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_firmsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('fresh', 'Fresh'), ('port', 'Port')], default='', max_length=10),
        ),
    ]
