# Generated by Django 4.2.25 on 2026-04-02 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='clients.employee'),
        ),
        migrations.AddField(
            model_name='renewal',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='renewal',
            name='premium_collected_on',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
