# Generated by Django 5.2.9 on 2026-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0050_renewal_employee_renewal_premium_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='renewal_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
