# Generated by Django 5.2.9 on 2026-04-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0051_renewal_renewal_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('domain', models.CharField(choices=[('sale', 'Sales'), ('renewal', 'Renewals'), ('both', 'Both')], default='both', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='product',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_rules', to='clients.product'),
        ),
        migrations.AddField(
            model_name='monthlytargethistory',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_target_histories', to='clients.product'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='clients.product'),
        ),
        migrations.AddField(
            model_name='renewal',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_entries', to='clients.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.product'),
        ),
        migrations.AddField(
            model_name='target',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='clients.product'),
        ),
    ]
