# Generated by Django 4.2.25 on 2026-04-13 08:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_seed_products_and_backfill_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmsettings',
            name='firm_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, help_text='Base unit (e.g., 1000 or 100000)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='monthlytargethistory',
            name='points_value',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
    ]
