# Generated by Django 5.2.9 on 2026-04-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_fix_points_decimal_firm_name_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='drive_folder_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
