# Generated by Django 5.2.9 on 2026-04-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='calling_list',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='related_prospect',
        ),
        migrations.DeleteModel(
            name='CallingList',
        ),
        migrations.DeleteModel(
            name='CallRecord',
        ),
        migrations.DeleteModel(
            name='Prospect',
        ),
    ]
