# Generated by Django 5.2.9 on 2026-05-04 06:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_drop_calling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_private', models.BooleanField(default=False, help_text='If true, only owner + admins can view. Otherwise see shared_with.')),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_lead_sheets', to='clients.employee')),
                ('product', models.ForeignKey(blank=True, help_text='Optional: which product this sheet is tracking leads for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_sheets', to='clients.product')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='If non-empty (and not private), these employees + owner + admins can view.', related_name='shared_lead_sheets', to='clients.employee')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name shown in the column header.', max_length=100)),
                ('field_key', models.SlugField(help_text='Internal key — record values are stored under this.', max_length=60)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('phone', 'Phone'), ('email', 'Email'), ('select', 'Dropdown'), ('status', 'Status badge')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text="For 'select' or 'status' types: list of allowed values.")),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='clients.leadsheet')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadSheetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_client', models.ForeignKey(blank=True, help_text='Set when this row has been converted into a Client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_lead_records', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='clients.leadsheet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='leadsheet',
            index=models.Index(fields=['owner', 'archived'], name='ls_owner_arch_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadsheetcolumn',
            unique_together={('sheet', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='leadsheetrecord',
            index=models.Index(fields=['sheet', '-created_at'], name='lsr_sheet_time_idx'),
        ),
    ]
