# Generated by Django 5.2.9 on 2026-05-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0059_lead_record_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsheetrecord',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
