# Generated by Django 5.2.9 on 2026-05-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0060_lead_record_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly')], max_length=15),
        ),
    ]
