# Generated by Django 5.2.9 on 2026-05-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_renewal_quarterly_halfyearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsheetrecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lead_records', to='clients.employee'),
        ),
    ]
