# Generated by Django 5.2.9 on 2026-05-19 06:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0062_lead_record_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Default business margin % on this product's revenue, used when no margin slab matches.", max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='ProductMarginSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(blank=True, choices=[('', 'All / Not applicable'), ('fresh', 'Fresh'), ('port', 'Port')], default='', help_text='Fresh / Port for Health Insurance; leave blank for other products.', max_length=10)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Lower bound of cumulative monthly revenue (inclusive).', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Upper bound (inclusive). Leave blank for the top 'and above' slab.", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('margin_percent', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_slabs', to='clients.product')),
            ],
            options={
                'verbose_name': 'Product Margin Slab',
                'verbose_name_plural': 'Product Margin Slabs',
                'ordering': ['product', 'policy_type', 'min_amount'],
            },
        ),
    ]
