# Generated by Django 5.2.9 on 2026-05-19 07:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0065_seed_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='renewal_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Business margin % applied to this product's renewal premium (only used for renewal-tracked products).", max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Default business margin % on this product's sale revenue, used when no margin slab matches.", max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
