# Generated by Django 5.2.9 on 2026-05-19 07:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0066_product_renewal_margin_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('equity_aum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('debt_aum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('hybrid_aum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('equity_trail_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('debt_trail_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('hybrid_trail_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_sip', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='New monthly SIP mobilised this month (adds to the SIP book).', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_lumpsum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lump sum mobilised this month.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('redemptions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='AUM redeemed this month.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('sip_stopped', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly SIP value stopped this month (reduces SIP book).', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('sip_book', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total active monthly SIP inflow as at month-end.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('annual_market_growth_pct', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Assumed annual market growth %.', max_digits=6)),
                ('redemption_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Assumed annual redemption % of AUM.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sip_stoppage_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Assumed annual SIP-stoppage % of the SIP book.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('projection_trail_pct', models.DecimalField(decimal_places=3, default=Decimal('0.750'), help_text='Blended annual trail % applied to new (projected) business.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MF Monthly Snapshot',
                'verbose_name_plural': 'MF Monthly Snapshots',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
