# Generated by Django 5.2.9 on 2026-05-19 07:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0067_mfmonthlysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfmonthlysnapshot',
            name='actual_insurance_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional: actual recurring insurance revenue this month (recurring base).', max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='mfmonthlysnapshot',
            name='actual_trail_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: actual trail received this month. Overrides the AUM×trail estimate.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
