# Generated by Django 5.2.9 on 2026-05-20 09:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0068_mfmonthlysnapshot_actual_insurance_revenue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFProjectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_market_growth_pct', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=6)),
                ('redemption_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sip_stoppage_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('projection_trail_pct', models.DecimalField(decimal_places=3, default=Decimal('0.750'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MF Projection Settings',
                'verbose_name_plural': 'MF Projection Settings',
            },
        ),
        migrations.CreateModel(
            name='MFSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('opening_aum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('closing_aum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('gross_sip_registered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='New monthly SIP value registered during this period.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('active_sip_book', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total active monthly SIP inflow at period end (₹/month).', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('stopped_sip_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly SIP value stopped/discontinued during this period.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_lumpsum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('redemptions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('trail_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total trail commission received during this period.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_new_business', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_renewals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MF Snapshot',
                'verbose_name_plural': 'MF Snapshots',
                'ordering': ['-start_date', '-end_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.DeleteModel(
            name='MFMonthlySnapshot',
        ),
    ]
