# Generated by Django 5.2.9 on 2026-05-20 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0069_mfprojectionsettings_mfsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfsnapshot',
            name='closing_aum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if unknown — projection uses the latest snapshot that does have a closing AUM.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mfsnapshot',
            name='opening_aum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if unknown for old periods — AUM-based metrics skip blanks gracefully.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
