# Generated by Django 5.2.9 on 2026-06-05 11:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0071_leadsheet_public_form_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Manual kill switch. A campaign only applies when active AND the sale date is within the window.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-end_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('unit', 'Custom points per unit'), ('target', 'One-time target payout')], default='unit', max_length=10)),
                ('unit_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Base unit (e.g., 1000). Used for the 'Custom points per unit' benefit.", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('points_per_unit', models.DecimalField(blank=True, decimal_places=3, help_text="Points awarded per unit_amount. Used for the 'Custom points per unit' benefit.", max_digits=12, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.campaign')),
                ('product_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_products', to='clients.product')),
            ],
            options={
                'unique_together': {('campaign', 'product_ref')},
            },
        ),
        migrations.CreateModel(
            name='CampaignSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Cumulative amount threshold within the campaign window.', max_digits=14)),
                ('payout', models.DecimalField(decimal_places=2, help_text='Points/payout awarded when the threshold is reached.', max_digits=14)),
                ('label', models.CharField(blank=True, help_text="Optional label, e.g. 'Gold Slab'", max_length=100)),
                ('campaign_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='clients.campaignproduct')),
            ],
            options={
                'ordering': ['-threshold'],
                'unique_together': {('campaign_product', 'threshold')},
            },
        ),
    ]
