# Generated by Django 5.2.9 on 2026-06-11 11:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0072_campaign_sale_campaign_campaignproduct_campaignslab'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, help_text='Monthly target for this employee on this product.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='clients.employee')),
                ('product_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_targets', to='clients.product')),
            ],
            options={
                'ordering': ['employee__user__username', 'product'],
                'unique_together': {('employee', 'product')},
            },
        ),
    ]
