# Generated by Django 5.2.9 on 2026-07-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0073_employeetarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(help_text='Employee responsible for this lead', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='clients.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clients.employee'),
        ),
    ]
