# Generated by Django 5.2.9 on 2026-07-02 10:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0075_pushdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('work_start', models.TimeField(default=datetime.time(10, 0))),
                ('work_end', models.TimeField(default=datetime.time(18, 0))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Tracking Settings',
                'verbose_name_plural': 'Call Tracking Settings',
            },
        ),
        migrations.CreateModel(
            name='CallFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=12)),
                ('reminded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_followups', to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_followups', to='clients.employee')),
            ],
            options={
                'ordering': ['status', 'scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('connected', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='Auto-matched by phone number.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='clients.employee')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['employee', '-started_at'], name='call_emp_time_idx')],
                'unique_together': {('employee', 'phone', 'started_at')},
            },
        ),
    ]
