# Generated by Django 5.2.9 on 2026-07-03 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0076_calltrackingsettings_callfollowup_calllogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls_granted', models.BooleanField(default=False)),
                ('overlay_granted', models.BooleanField(default=False)),
                ('notifications_granted', models.BooleanField(default=False)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_device_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Device Status',
                'verbose_name_plural': 'App Device Statuses',
            },
        ),
    ]
