# Generated by Django 5.2.9 on 2026-07-05 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0077_appdevicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltrackingsettings',
            name='popup_days',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text='Weekdays the post-call popup appears. Default every day.', max_length=20),
        ),
        migrations.AddField(
            model_name='calltrackingsettings',
            name='popup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calltrackingsettings',
            name='popup_end',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AddField(
            model_name='calltrackingsettings',
            name='popup_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='calltrackingsettings',
            name='work_days',
            field=models.CharField(default='0,1,2,3,4,5', help_text='Weekdays counted in analytics. 0=Mon … 6=Sun. Default Mon–Sat.', max_length=20),
        ),
    ]
