# Generated by Django 5.2.9 on 2026-07-05 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0079_task_taskactivity_taskattachment_taskcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_day_before', models.BooleanField(default=True)),
                ('remind_same_day', models.BooleanField(default=True)),
                ('same_day_hour', models.PositiveSmallIntegerField(default=9, help_text='Hour (0-23) to send the same-day / day-before reminder.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task reminder settings',
                'verbose_name_plural': 'Task reminder settings',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='reminded_day_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminded_same_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_rule',
            field=models.CharField(blank=True, help_text="Recurrence frequency shown on the task: '', daily, weekly, monthly, custom.", max_length=20),
        ),
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('icon', models.CharField(default='bi-link-45deg', max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Link categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Optional Bootstrap icon class; else the category icon is used.', max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='clients.linkcategory')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LinkFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='clients.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_assigned', models.BooleanField(default=True)),
                ('notify_status_changed', models.BooleanField(default=True)),
                ('notify_due_changed', models.BooleanField(default=True)),
                ('notify_priority_changed', models.BooleanField(default=True)),
                ('notify_comment_added', models.BooleanField(default=True)),
                ('notify_checklist_updated', models.BooleanField(default=True)),
                ('notify_attachment_added', models.BooleanField(default=True)),
                ('notify_voicenote_added', models.BooleanField(default=True)),
                ('notify_completed', models.BooleanField(default=True)),
                ('notify_subscriber_added', models.BooleanField(default=True)),
                ('notify_overdue', models.BooleanField(default=True)),
                ('notify_recurring_created', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_notification_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTaskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('checklist_template', models.TextField(blank=True, help_text='One checklist item per line; copied onto each instance.')),
                ('subscriber_ids', models.CharField(blank=True, help_text='CSV of User ids added In-Loop to each instance.', max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Every N days/weeks/months.')),
                ('weekdays', models.CharField(blank=True, help_text='For weekly/custom: CSV weekday numbers, 0=Mon … 6=Sun.', max_length=20)),
                ('start_date', models.DateField()),
                ('end_type', models.CharField(choices=[('never', 'Never'), ('on_date', 'On date'), ('after_n', 'After N occurrences')], default='never', max_length=10)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, null=True)),
                ('occurrences_created', models.PositiveIntegerField(default=0)),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.employee')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.taskcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='clients.recurringtaskrule'),
        ),
        migrations.CreateModel(
            name='SavedTaskFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('query_string', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_task_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['category', 'display_order'], name='link_cat_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linkfavorite',
            unique_together={('user', 'link')},
        ),
        migrations.AlterUniqueTogether(
            name='savedtaskfilter',
            unique_together={('user', 'name')},
        ),
    ]
