# Generated by Django 5.2.9 on 2026-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0080_taskremindersetting_task_reminded_day_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='WhatsApp number for task notifications (with or without +91).', max_length=20),
        ),
        migrations.AddField(
            model_name='taskremindersetting',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(default=9, help_text='Hour (0-23) to send the daily task digest.'),
        ),
        migrations.AddField(
            model_name='taskremindersetting',
            name='send_daily_digest',
            field=models.BooleanField(default=True, help_text='Send each employee a morning WhatsApp summary of their open tasks.'),
        ),
    ]
