# Generated by Django 4.2.25 on 2026-07-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0080_taskremindersetting_task_reminded_day_before_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mfsnapshot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mfsnapshot',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MFProjectionSettings',
        ),
        migrations.DeleteModel(
            name='MFSnapshot',
        ),
    ]
