# Generated by Django 5.2.9 on 2026-07-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0082_alter_mfsnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltrackingsettings',
            name='popup_choices',
            field=models.CharField(default='10m,15m,30m,1h,2h,3h,4h,1d,5d,10d,1w,2w,1mo,2mo', help_text='Comma-separated quick-chip keys shown on the post-call popup.', max_length=250),
        ),
    ]
