# Generated by Django 5.2.16 on 2026-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0083_calltrackingsettings_popup_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdevicestatus',
            name='diagnostics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
