# Generated by Django 5.2.16 on 2026-07-14 14:42

import datetime
from django.db import migrations, models


def make_popup_always_on(apps, schema_editor):
    """Owner decision 2026-07-14: the post-call popup must be available 24×7.
    Force the live settings row to enabled, all-day, every day — whatever was
    saved before (a narrowed window silently suppressed popups on phones)."""
    CallTrackingSettings = apps.get_model("clients", "CallTrackingSettings")
    CallTrackingSettings.objects.update(
        popup_enabled=True,
        popup_start=datetime.time(0, 0),
        popup_end=datetime.time(23, 59),
        popup_days="0,1,2,3,4,5,6",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0084_appdevicestatus_diagnostics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltrackingsettings',
            name='popup_end',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='calltrackingsettings',
            name='popup_start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.RunPython(make_popup_always_on, migrations.RunPython.noop),
    ]
