# Generated by Django 5.2.16 on 2026-07-14 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0085_alter_calltrackingsettings_popup_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ack_last_rung_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.client'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_alarm_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Task Created'), ('assigned', 'Task Assigned'), ('subscriber_added', 'Subscriber Added'), ('priority_changed', 'Priority Changed'), ('category_changed', 'Category Changed'), ('description_updated', 'Description Updated'), ('checklist_updated', 'Checklist Updated'), ('attachment_uploaded', 'Attachment Uploaded'), ('voicenote_uploaded', 'Voice Note Uploaded'), ('comment_added', 'Comment Added'), ('due_changed', 'Due Date Changed'), ('status_changed', 'Status Changed'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('restored', 'Restored'), ('acknowledged', 'Acknowledged')], db_index=True, max_length=25),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('checklist', models.TextField(blank=True, default='', help_text='One checklist item per line.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.taskcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
