# Generated by Django 5.2.16 on 2026-07-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0086_task_ack_last_rung_at_task_acknowledged_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArnAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Direct (NSE)' or 'NJ'", max_length=80, unique=True)),
                ('arn_code', models.CharField(help_text='As it appears in RTA files, e.g. ARN-152880', max_length=40)),
                ('sub_broker_code', models.CharField(blank=True, default='', help_text='Required for platform-routed business (e.g. NJ partner code)', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(db_index=True, max_length=40)),
                ('amc_name', models.CharField(blank=True, default='', max_length=120)),
                ('rta', models.CharField(blank=True, choices=[('CAMS', 'CAMS'), ('KFIN', 'KFintech')], default='', max_length=8)),
                ('investor_name', models.CharField(blank=True, default='', max_length=200)),
                ('pan', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='clients.arnaccount')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mf_folios', to='clients.client')),
            ],
            options={
                'ordering': ['investor_name', 'folio_number'],
                'unique_together': {('folio_number', 'amc_name')},
            },
        ),
        migrations.CreateModel(
            name='RTAFeedImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rta', models.CharField(blank=True, choices=[('CAMS', 'CAMS'), ('KFIN', 'KFintech')], default='', max_length=8)),
                ('source', models.CharField(choices=[('email', 'Email'), ('upload', 'Upload')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='processed', max_length=10)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_duplicate', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('folios_created', models.IntegerField(default=0)),
                ('clients_linked', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rta', models.CharField(blank=True, choices=[('CAMS', 'CAMS'), ('KFIN', 'KFintech')], default='', max_length=8)),
                ('scheme_name', models.CharField(blank=True, default='', max_length=200)),
                ('txn_type', models.CharField(blank=True, default='', max_length=80)),
                ('txn_number', models.CharField(blank=True, default='', max_length=60)),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('broker_code', models.CharField(blank=True, default='', max_length=40)),
                ('sub_broker_code', models.CharField(blank=True, default='', max_length=40)),
                ('dedupe_key', models.CharField(max_length=40, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('arn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mf_transactions', to='clients.arnaccount')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.mutualfundfolio')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='clients.rtafeedimport')),
            ],
            options={
                'ordering': ['-trade_date', '-id'],
                'indexes': [models.Index(fields=['trade_date'], name='mftxn_trade_date_idx'), models.Index(fields=['arn', 'trade_date'], name='mftxn_arn_date_idx')],
            },
        ),
    ]
