# Generated by Django 5.2.16 on 2026-07-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0087_arnaccount_mutualfundfolio_rtafeedimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rta_match',
            field=models.CharField(blank=True, choices=[('', 'Not RTA-linked'), ('sip', 'MF SIP installments'), ('lumpsum', 'MF lumpsum purchases'), ('any', 'Any MF transaction')], default='', help_text='If set, pending sales of this product are cross-checked against RTA feed transactions by client PAN.', max_length=10),
        ),
    ]
