# Generated by Django 5.2.16 on 2026-07-16 06:41
#
# Adds the `reminded` flag consumed by send_followup_reminders (which now
# reminds for lead follow-ups and calendar events, not just call follow-ups).
# The backfill marks anything already past-due as reminded so the first cron
# run after deploy doesn't flood everyone with notifications for old items.

from django.db import migrations, models
from django.utils import timezone


def backfill_reminded(apps, schema_editor):
    now = timezone.now()
    apps.get_model("clients", "LeadFollowUp").objects.filter(
        scheduled_time__lte=now
    ).update(reminded=True)
    apps.get_model("clients", "CalendarEvent").objects.filter(
        scheduled_time__lte=now
    ).update(reminded=True)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0089_remove_leadsheetrecord_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_reminded, migrations.RunPython.noop),
    ]
