# Generated by Django 5.2.16 on 2026-07-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0090_calendarevent_reminded_leadfollowup_reminded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyIncentive',
        ),
    ]
