# Generated by Django 5.2.16 on 2026-07-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0091_delete_monthlyincentive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rta', models.CharField(blank=True, choices=[('CAMS', 'CAMS'), ('KFIN', 'KFintech')], default='', max_length=8)),
                ('registration_ref', models.CharField(blank=True, default='', max_length=60)),
                ('folio_number', models.CharField(db_index=True, max_length=40)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('investor_name', models.CharField(blank=True, default='', max_length=200)),
                ('amc_name', models.CharField(blank=True, default='', max_length=120)),
                ('scheme_name', models.CharField(blank=True, default='', max_length=200)),
                ('txn_type', models.CharField(blank=True, default='SIP', help_text='SIP / STP / SWP as reported by the RTA', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('frequency', models.CharField(blank=True, default='', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registered_on', models.DateField(blank=True, null=True)),
                ('installments', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ceased', 'Ceased')], db_index=True, default='active', max_length=10)),
                ('ceased_on', models.DateField(blank=True, null=True)),
                ('broker_code', models.CharField(blank=True, default='', max_length=40)),
                ('sub_broker_code', models.CharField(blank=True, default='', max_length=40)),
                ('dedupe_key', models.CharField(max_length=40, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_registrations', to='clients.arnaccount')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_registrations', to='clients.client')),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_registrations', to='clients.mutualfundfolio')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_registrations', to='clients.rtafeedimport')),
            ],
            options={
                'ordering': ['-registered_on', '-first_seen_at'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='sipreg_status_start_idx')],
            },
        ),
    ]
