# Generated by Django 5.2.16 on 2026-07-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0092_sipregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipregistration',
            name='rta_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
