# Generated by Django 5.2.16 on 2026-07-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0093_sipregistration_rta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipregistration',
            name='broker_name',
            field=models.CharField(blank=True, default='', help_text='Agent name as reported by the RTA — identifies foreign codes on the COB page', max_length=120),
        ),
    ]
