# Generated by Django 5.2.16 on 2026-07-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0094_sipregistration_broker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assign_group',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
