# Generated by Django 5.2.16 on 2026-07-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0095_task_assign_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(help_text='Short household code, e.g. A001.', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, help_text='Primary investor / group head.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_family', to='clients.client')),
                ('relationship_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='clients.employee')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clients.family'),
        ),
    ]
