# Generated by Django 5.2.16 on 2026-07-20 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0096_family_client_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, max_length=60)),
                ('insurer', models.CharField(help_text='Insurance company, e.g. ICICI Lombard.', max_length=120)),
                ('plan_name', models.CharField(blank=True, max_length=160)),
                ('insurance_type', models.CharField(choices=[('health', 'Health'), ('life', 'Life'), ('motor', 'Motor'), ('other', 'Other')], default='health', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lapsed', 'Lapsed'), ('matured', 'Matured'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10)),
                ('sum_insured', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=120)),
                ('nominee_relationship', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='clients.client')),
                ('relationship_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='clients.employee')),
            ],
            options={
                'verbose_name_plural': 'Insurance policies',
                'ordering': ['-end_date', 'policy_number'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(blank=True, help_text='e.g. Hospitalisation Claim.', max_length=120)),
                ('claim_mode', models.CharField(choices=[('cashless', 'Cashless'), ('reimbursement', 'Reimbursement')], default='cashless', max_length=15)),
                ('status', models.CharField(choices=[('intimated', 'Intimated'), ('file_received', 'File Received'), ('submitted', 'Submitted'), ('settled', 'Settled'), ('rejected', 'Rejected')], db_index=True, default='intimated', max_length=15)),
                ('intimation_date', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('settlement_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='clients.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='clients.insurancepolicy')),
            ],
            options={
                'ordering': ['-intimation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('review', 'Portfolio Review'), ('onboarding', 'Onboarding'), ('service', 'Service'), ('sales', 'Sales')], default='review', max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=10)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('next_meeting_date', models.DateField(blank=True, db_index=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='clients.employee')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
