# Generated by Django 5.2.16 on 2026-07-20 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0098_employee_address_employee_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('birthday', 'Birthday'), ('work_anniversary', 'Work Anniversary'), ('long_service', 'Long Service'), ('qualification', 'Qualification / Certification'), ('target_beaten', 'Target Beaten'), ('promotion', 'Promotion'), ('appreciation', 'Appreciation')], max_length=20)),
                ('occurs_on', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('years', models.PositiveIntegerField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('celebrated_at', models.DateTimeField(blank=True, null=True)),
                ('celebration_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celebrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='clients.employee')),
            ],
            options={
                'ordering': ['occurs_on', 'employee__user__username'],
                'unique_together': {('employee', 'kind', 'occurs_on')},
            },
        ),
    ]
