# Generated by Django 5.2.16 on 2026-07-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0099_employeemilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='policy_date',
            field=models.DateField(blank=True, db_index=True, help_text='Policy commencement date from the policy document (drives the annual renewal reminder). Insurance only.', null=True),
        ),
    ]
