# Generated by Django 5.2.16 on 2026-07-21 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0100_sale_policy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='source_sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy', to='clients.sale'),
        ),
    ]
