# Generated by Django 5.2.16 on 2026-07-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0101_insurancepolicy_source_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='clients.insurancepolicy'),
        ),
        migrations.AddField(
            model_name='sale',
            name='policy_number',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
