# Generated by Django 5.2.16 on 2026-07-21 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0102_renewal_policy_sale_policy_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Claim raised'), ('status_changed', 'Stage changed'), ('note', 'Note added'), ('document_added', 'Document added'), ('document_removed', 'Document removed'), ('reminder_set', 'Reminder set'), ('reminder_done', 'Reminder completed')], db_index=True, max_length=20)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clients.insuranceclaim')),
            ],
            options={
                'verbose_name_plural': 'Claim activities',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('claim_form', 'Claim Form'), ('bill', 'Bill / Invoice'), ('discharge', 'Discharge Summary'), ('prescription', 'Prescription / Reports'), ('id_proof', 'ID Proof'), ('settlement', 'Settlement Letter'), ('other', 'Other')], default='other', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('drive_file_id', models.CharField(max_length=128)),
                ('drive_view_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.insuranceclaim')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=12)),
                ('reminded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clients.insuranceclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_reminders', to='clients.employee')),
            ],
            options={
                'ordering': ['status', 'scheduled_at'],
            },
        ),
    ]
