# Generated by Django 5.2.16 on 2026-07-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0103_claimactivity_claimdocument_claimreminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_relation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='prior_experience_months',
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=10),
        ),
    ]
