# Generated by Django 5.2.16 on 2026-07-23 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0105_sync_employee_names_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Optional category. Set this to make the product a sub-product (e.g. 'Term Plan' under 'Life Insurance') — it inherits the category's insurance behaviour and carries its own margin.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='clients.product'),
        ),
    ]
