# Generated by Django 5.2.16 on 2026-07-23 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0106_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsettings',
            name='mdrt_active_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlanPptRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('advisor', 'Advisor'), ('mdrt', 'MDRT')], default='advisor', max_length=10)),
                ('ppt', models.CharField(help_text='Premium Paying Term: "SP" (single premium), or years like "5", "12+".', max_length=4)),
                ('fyc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='First-year commission %')),
                ('ryc_2nd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Renewal % (2nd yr)')),
                ('ryc_3rd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Renewal % (3rd yr)')),
                ('ryc_4th', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Renewal % (4th yr)')),
                ('ryc_5plus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Renewal % (5+ yr)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppt_rates', to='clients.product')),
            ],
            options={
                'verbose_name': 'Plan PPT Rate',
                'verbose_name_plural': 'Plan PPT Rates',
                'ordering': ['product', 'designation', 'ppt'],
                'unique_together': {('product', 'designation', 'ppt')},
            },
        ),
    ]
