# Generated by Django 5.2.16 on 2026-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0107_planpptrate_mdrt_active_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='margin_percent_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='FYC % locked in at sale time for PPT-priced plans.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='ppt',
            field=models.CharField(blank=True, default='', help_text="Premium Paying Term for PPT-priced life plans (e.g. '10', '12+', 'SP').", max_length=4),
        ),
    ]
