# Generated by Django 5.2.16 on 2026-07-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0108_sale_margin_percent_snapshot_sale_ppt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='emi_months',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not on EMI'), (5, '5 months'), (8, '8 months'), (11, '11 months')], default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='policy_years',
            field=models.PositiveSmallIntegerField(default=1, help_text='Years the (multiyear) policy covers. 1 = ordinary single-year sale.'),
        ),
    ]
