# Generated by Django 5.2.16 on 2026-07-29 10:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0109_sale_emi_months_sale_policy_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiverule',
            name='port_percent',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Health insurance only: flat % paid on Port policies, which sit outside the Fresh volume ladder. Blank = Port earns nothing.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='slab_mode',
            field=models.CharField(choices=[('bonus', 'Slab payout is a rupee bonus (earned-to-date ladder)'), ('rate', 'Slab payout is a % rate applied to the sale')], default='bonus', help_text="How this rule's slab payouts are read.", max_length=10),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='slab_period',
            field=models.CharField(choices=[('month', 'Calendar month'), ('fy', 'Financial year (Apr–Mar)')], default='month', help_text='Window the cumulative volume driving the slabs is measured over.', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='bonus_points',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='incentiveslab',
            name='payout',
            field=models.DecimalField(decimal_places=2, help_text='Rupees earned-to-date at this threshold (bonus mode), or the % rate paid on each sale in this band (rate mode)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='incentiveslab',
            name='threshold',
            field=models.DecimalField(decimal_places=2, help_text="Cumulative amount threshold, over the rule's slab period", max_digits=14),
        ),
    ]
