# Generated by Django 5.2.16 on 2026-07-29 11:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0111_backfill_bonus_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_index', models.PositiveSmallIntegerField(help_text='Which policy year these points are for (2 = second year).')),
                ('due_date', models.DateField(db_index=True, help_text='The policy anniversary these points fell due on.')),
                ('amount', models.DecimalField(decimal_places=2, help_text="The year's premium slice these points were computed on.", max_digits=14)),
                ('points', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incentive_accruals', to='clients.employee')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='clients.sale')),
            ],
            options={
                'verbose_name': 'Incentive Accrual',
                'verbose_name_plural': 'Incentive Accruals',
                'ordering': ['-due_date', '-id'],
                'indexes': [models.Index(fields=['employee', 'due_date'], name='accrual_emp_due_idx')],
                'unique_together': {('sale', 'year_index')},
            },
        ),
    ]
