# Generated by Django 5.2.16 on 2026-07-29 17:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0112_incentiveaccrual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_month', models.DateField(db_index=True, help_text='The month this payout was for, stored as its 1st.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rupees paid. Counts as ladder bonus already released.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_payouts', to='clients.employee')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='clients.incentiverule')),
            ],
            options={
                'verbose_name': 'Bonus Payout (manual)',
                'verbose_name_plural': 'Bonus Payouts (manual)',
                'ordering': ['-for_month', '-id'],
                'unique_together': {('employee', 'rule', 'for_month')},
            },
        ),
    ]
