# Generated by Django 5.2.16 on 2026-07-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0113_bonuspayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiverule',
            name='deduct_legacy_monthly',
            field=models.BooleanField(default=False, help_text="Subtract the old monthly slab payout from this ladder, derived from each month's volume. Turn off once the monthly bonus stops."),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='legacy_deduct_from',
            field=models.DateField(blank=True, help_text='Only derive the deduction for months on or after this date. Earlier months were already netted when the structure changed.', null=True),
        ),
    ]
