# Generated by Django 5.2.16 on 2026-07-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0114_incentiverule_deduct_legacy_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callfollowup',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='callfollowup',
            name='outcome',
            field=models.CharField(blank=True, choices=[('spoke', 'Spoke'), ('no_answer', 'No answer'), ('call_back', 'Call back later'), ('not_interested', 'Not interested'), ('converted', 'Converted')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='callfollowup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('dismissed', 'Dismissed'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=12),
        ),
    ]
