# Generated by Django 5.2.16 on 2026-07-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0115_callfollowup_attempts_callfollowup_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentiverule',
            name='deduct_legacy_monthly',
        ),
        migrations.RemoveField(
            model_name='incentiverule',
            name='legacy_deduct_from',
        ),
    ]
