# Generated by Django 5.2.16 on 2026-07-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0116_remove_incentiverule_deduct_legacy_monthly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentiverule',
            name='port_percent',
        ),
    ]
