# Generated by Django 5.2.16 on 2026-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0119_spanco_lead_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
