# Generated by Django 5.2.16 on 2026-08-14 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0120_alter_sale_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source_kind', 'source_id'], name='task_source_idx'),
        ),
    ]
