# Generated by Django 5.2.16 on 2026-08-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_followups_become_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadfollowup',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='leadfollowup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leadfollowup',
            name='lead',
        ),
        migrations.DeleteModel(
            name='ClaimReminder',
        ),
        migrations.DeleteModel(
            name='LeadFollowUp',
        ),
    ]
