# Generated by Django 5.2.16 on 2026-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0123_drop_followup_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='silent',
            field=models.BooleanField(default=False, help_text='Notify quietly — no ringing alarm on the phone.'),
        ),
    ]
