# Generated by Django 5.2.16 on 2026-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0124_task_silent'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='policy_doc_submitted',
            field=models.BooleanField(default=False, verbose_name='Renewal policy submitted to Google Drive'),
        ),
    ]
