# Generated by Django 5.2.16 on 2026-09-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0126_drop_mutual_funds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
