# Generated by Django 5.2.16 on 2026-09-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0127_delete_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='policy_doc_submitted',
            field=models.BooleanField(default=False, verbose_name='Policy uploaded to Google Drive'),
        ),
    ]
