# Generated by Django 5.2.16 on 2026-09-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0128_sale_policy_doc_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Other employees working this lead alongside the owner.', related_name='collaborating_leads', to='clients.employee'),
        ),
    ]
