# Generated by Django 5.2.16 on 2026-09-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0129_lead_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_reports',
            field=models.BooleanField(default=True, help_text='Show this product as a column on the daily/monthly business report. Turn it off for a product nobody reads on that sheet — the sales themselves are unaffected.'),
        ),
    ]
