# Generated by Django 5.2.16 on 2026-09-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0130_product_show_in_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='insurer',
            field=models.CharField(blank=True, max_length=120, verbose_name='Policy company'),
        ),
    ]
