# Generated by Django 5.2.16 on 2026-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0131_sale_insurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
