# Generated by Django 5.2.16 on 2026-09-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0132_lead_drive_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('health', 'Health Insurance'), ('term', 'Term Life'), ('endowment', 'Endowment'), ('money_back', 'Money Back'), ('whole_life', 'Whole Life'), ('child', 'Child Plan'), ('ulip', 'ULIP'), ('pension', 'Pension / Annuity'), ('motor', 'Motor'), ('other', 'Other')], default='endowment', max_length=12)),
                ('insurer', models.CharField(help_text='e.g. LIC, HDFC Life, Star Health.', max_length=120)),
                ('plan_name', models.CharField(blank=True, max_length=160)),
                ('policy_number', models.CharField(blank=True, db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('active', 'In force'), ('paid_up', 'Paid-up'), ('lapsed', 'Lapsed'), ('surrendered', 'Surrendered'), ('matured', 'Matured')], db_index=True, default='active', max_length=12)),
                ('sum_assured', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('premium_frequency', models.PositiveSmallIntegerField(choices=[(12, 'Yearly'), (6, 'Half-yearly'), (3, 'Quarterly'), (1, 'Monthly'), (0, 'Single premium')], default=12)),
                ('start_date', models.DateField(help_text='Commencement date on the policy document.')),
                ('premium_paying_term', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('policy_term', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, db_index=True, null=True)),
                ('maturity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_accrued', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payout_every_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pension_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pension_frequency', models.PositiveSmallIntegerField(blank=True, choices=[(12, 'Yearly'), (6, 'Half-yearly'), (3, 'Quarterly'), (1, 'Monthly')], null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=120)),
                ('nominee_relationship', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_policies', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'External policies',
                'ordering': ['start_date', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('policy_number', ''), _negated=True), fields=('client', 'policy_number'), name='extpolicy_unique_number_per_client', violation_error_message='This client already has an external policy with this number.')],
            },
        ),
    ]
