# Generated by Django 5.2.16 on 2026-10-02 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0133_external_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='loss_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='loss_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadinterest',
            name='cover_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum assured / cover being discussed (insurance). Not counted as value.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leadinterest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly premium for insurance, the monthly instalment for a SIP, else the amount to invest. Optional.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
