# Generated by Django 5.2.16 on 2026-10-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0134_lead_value_cover_loss_signoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='premium_mode',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('half_yearly', 'Half-yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='yearly', max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='yearly_premium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Life: the policy's annual premium as entered. Blank on older rows.", max_digits=14, null=True),
        ),
    ]
