# Generated by Django 5.2.16 on 2026-10-03 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0135_sale_life_premium_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='task_created_idx'),
        ),
    ]
