# Generated by Django 5.2.16 on 2026-10-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0137_tax_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxharvest',
            name='reinvested_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxharvest',
            name='reinvestment',
            field=models.CharField(blank=True, choices=[('mf', 'Repurchased in mutual fund'), ('insurance', 'Converted to insurance')], max_length=10),
        ),
    ]
