"""Native Android app JSON API (session-cookie auth) + APK download."""
from django.urls import path

from ..views import app_api, app_insurance_api, app_settings_api, app_tasks_api

urlpatterns = [
    path("api/app/tasks/", app_tasks_api.app_tasks, name="app_tasks"),
    path("api/app/tasks/meta/", app_tasks_api.app_task_meta, name="app_task_meta"),
    path("api/app/tasks/activities/", app_tasks_api.app_task_activities, name="app_task_activities"),
    path("api/app/tasks/scorecard/", app_tasks_api.app_task_scorecard, name="app_task_scorecard"),
    path("api/app/tasks/categories/create/", app_tasks_api.app_task_category_create, name="app_task_category_create"),
    path("api/app/tasks/templates/", app_tasks_api.app_task_templates, name="app_task_templates"),
    path("api/app/tasks/templates/save/", app_tasks_api.app_task_template_save, name="app_task_template_save"),
    path("api/app/tasks/create/", app_tasks_api.app_task_create, name="app_task_create"),
    path("api/app/tasks/<int:pk>/", app_tasks_api.app_task_detail, name="app_task_detail"),
    path("api/app/tasks/<int:pk>/action/", app_tasks_api.app_task_action, name="app_task_action"),
    path("api/app/links/", app_tasks_api.app_links, name="app_links"),
    path("api/app/links/create/", app_tasks_api.app_link_create, name="app_link_create"),
    path("api/app/links/<int:link_id>/favorite/", app_tasks_api.app_link_favorite, name="app_link_favorite"),
    path("api/app/me/", app_api.app_me, name="app_me"),
    path("api/app/dashboard/", app_api.app_dashboard, name="app_dashboard"),
    path("api/app/sale-meta/", app_api.app_sale_meta, name="app_sale_meta"),
    path("api/app/sales/create/", app_api.app_sale_create, name="app_sale_create"),
    path("api/app/sales/", app_api.app_sales, name="app_sales"),
    path("api/app/sales/<int:sale_id>/action/", app_api.app_sale_action, name="app_sale_action"),
    path("api/app/clients/", app_api.app_clients, name="app_clients"),
    path("api/app/clients/create/", app_api.app_client_create, name="app_client_create"),
    path("api/app/clients/<int:client_id>/", app_api.app_client_detail, name="app_client_detail"),
    path("api/app/followups/", app_api.app_followups, name="app_followups"),
    path("api/app/followups/<int:followup_id>/action/", app_api.app_followup_action, name="app_followup_action"),
    path("api/app/followups/push-overdue/", app_api.app_followups_push_overdue, name="app_followups_push_overdue"),
    path("api/app/logout/", app_api.app_logout, name="app_logout"),
    path("api/app/renewal-meta/", app_api.app_renewal_meta, name="app_renewal_meta"),
    path("api/app/renewals/", app_api.app_renewals, name="app_renewals"),
    path("api/app/renewals/create/", app_api.app_renewal_create, name="app_renewal_create"),
    path("api/app/notifications/", app_api.app_notifications, name="app_notifications"),
    path("api/app/notifications/read/", app_api.app_notifications_read, name="app_notifications_read"),
    path("api/app/insurance-meta/", app_insurance_api.app_insurance_meta, name="app_insurance_meta"),
    path("api/app/policies/", app_insurance_api.app_policies, name="app_policies"),
    path("api/app/policies/<int:policy_id>/", app_insurance_api.app_policy_detail, name="app_policy_detail"),
    path("api/app/claims/", app_insurance_api.app_claims, name="app_claims"),
    path("api/app/claims/create/", app_insurance_api.app_claim_create, name="app_claim_create"),
    path("api/app/claims/<int:claim_id>/", app_insurance_api.app_claim_detail, name="app_claim_detail"),
    path("api/app/claims/<int:claim_id>/update/", app_insurance_api.app_claim_update, name="app_claim_update"),
    path("api/app/claims/<int:claim_id>/document/", app_insurance_api.app_claim_document_upload,
         name="app_claim_document_upload"),
    path("api/app/lead-meta/", app_api.app_lead_meta, name="app_lead_meta"),
    path("api/app/leads/", app_api.app_leads, name="app_leads"),
    path("api/app/leads/create/", app_api.app_lead_create, name="app_lead_create"),
    path("api/app/leads/<int:lead_id>/", app_api.app_lead_detail, name="app_lead_detail"),
    path("api/app/leads/<int:lead_id>/stage/", app_api.app_lead_stage, name="app_lead_stage"),
    path("api/app/leads/<int:lead_id>/interest/", app_api.app_lead_interest, name="app_lead_interest"),
    path("api/app/leads/<int:lead_id>/remark/", app_api.app_lead_remark, name="app_lead_remark"),
    path("api/app/leads/<int:lead_id>/action/", app_api.app_lead_action, name="app_lead_action"),
    path("api/app/reports/summary/", app_api.app_report_summary, name="app_report_summary"),
    path("api/app/reports/monthly/", app_api.app_report_monthly, name="app_report_monthly"),
    path("api/app/reports/past/", app_api.app_report_past, name="app_report_past"),
    path("api/app/device-status/", app_api.app_device_status, name="app_device_status"),
    path("api/app/crash/", app_api.app_crash, name="app_crash"),
    path("api/app/calls/analytics/", app_api.app_call_analytics, name="app_call_analytics"),
    path("api/app/sheets/", app_api.app_sheets, name="app_sheets"),
    path("api/app/sheets/<int:sheet_id>/", app_api.app_sheet_records, name="app_sheet_records"),
    path("api/app/sheets/<int:sheet_id>/save/", app_api.app_sheet_record_save, name="app_sheet_record_save"),
    path("api/app/incentives/", app_api.app_incentives, name="app_incentives"),
    path("api/app/campaigns/", app_api.app_campaigns, name="app_campaigns"),
    path("api/app/team/", app_api.app_team, name="app_team"),
    path("api/app/team/create/", app_api.app_team_create, name="app_team_create"),
    path("api/app/team/<int:employee_id>/", app_api.app_team_detail, name="app_team_detail"),
    path("api/app/team/<int:employee_id>/update/", app_api.app_team_update, name="app_team_update"),
    path("api/app/team/<int:employee_id>/toggle/", app_api.app_team_toggle, name="app_team_toggle"),
    path("api/app/team/<int:employee_id>/reset-password/", app_api.app_team_reset_password, name="app_team_reset_password"),
    path("api/app/login/", app_api.app_login, name="app_login"),
    path("api/app/settings/", app_settings_api.app_settings, name="app_settings"),
    path("api/app/version/", app_api.app_version, name="app_version"),
    path("app/latest.apk", app_api.app_apk_download, name="app_apk_download"),
]
